### ISSUE TITLE
Can't open any docs

### ISSUE THREAD

**Issue by I-Own-You** [luckasRanarison/nvim-devdocs#23]
After update, i cant open any docs, i get this error:

![Screenshot from 2023-08-15 21-31-51](https://github.com/luckasRanarison/nvim-devdocs/assets/91146968/948caf6e-525d-4a11-8c51-1075e28218e9)

**Comment by I-Own-You** [comment]
> The old docs are incompatible with the plugin now, please delete all the old ones and the index.json

okay, reinstalling the plugin(it was faster then  to delete the docs) resolved the problem with freezing the neovim window, but i still cant open docs

**Comment by luckasRanarison** [comment]
You need to **DELETE** the old docs and the index.json, please take a look at the `release notes`

**Comment by I-Own-You** [comment]
> You need to **DELETE** the old docs and the index.json, please take a look at the `release notes`

![Screenshot from 2023-08-15 21-47-39](https://github.com/luckasRanarison/nvim-devdocs/assets/91146968/709fb46e-a117-47b4-beab-73ede563a19e)

as i said, i _**deleted**_ it.

**Comment by luckasRanarison** [comment]
Hum, does the picker preview work correctly?

**Comment by I-Own-You** [comment]
opening the picker window and displaying the info on the right side ? **yes**

**Comment by luckasRanarison** [comment]
Can you provide detailed steps for reproducing it or a video?

**Comment by I-Own-You** [comment]
[Screencast from 2023-08-15 22-02-39.webm](https://github.com/luckasRanarison/nvim-devdocs/assets/91146968/1bc2b50d-dc3d-4832-8262-e4401f7dc491)

**Comment by I-Own-You** [comment]
> 

[Screencast from 2023-08-15 22-05-27.webm](https://github.com/luckasRanarison/nvim-devdocs/assets/91146968/e171870f-b46e-4132-9ba6-4003225013ae)

**Comment by luckasRanarison** [comment]
Does it work when not using cmd in the picker?

**Comment by I-Own-You** [comment]
it gives me error anyway, but setting `picker_cmd = true` instead of false(which is default), fixes the issue

**Comment by luckasRanarison** [comment]
It was a dumb typing error should be fixed now

**Comment by SuyogSoti** [comment]
https://github.com/luckasRanarison/nvim-devdocs/assets/13604256/013a1ee5-3b6a-4348-ad64-11a7ea27511e

Fresh installation today. The error still shows up regardless of whether picker_cmd is true or not (mine is set to true).

**Comment by SuyogSoti** [comment]
Ah slightly different exception. Fixed after I set the following setting:
```lua
        mappings = { -- keymaps for the doc buffer
          open_in_browser = "C-~"
        },
```
I believe the default throws an exception

**Comment by luckasRanarison** [comment]
> Ah slightly different exception. Fixed after I set the following setting:
> ```lua
>         mappings = { -- keymaps for the doc buffer
>           open_in_browser = "C-~"
>         },
> ```
> I believe the default throws an exception

Sorry for the late reply. I just saw your comment now. It was caused by the default mapping which was an empty string, and it's fixed now.

The issue with the picker previewer has already been fixed a while ago so I'm also closing this.
